baseurl: https://example.com
title: Casually Gaussian
author: Rodrigo L. Ferreira
canonifyurls: yes
languagecode: en
theme: hugo-tanka
enableEmoji: yes
hasCJKLanguage: no
pygmentsstyle: vs
pygmentscodefences: yes
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
params:
  faviconfile: images/pexels-maria-orlova-4946412.jpg
  highlightjs: yes
  highlightjslanguages:
    - r
    - python
    - stan
  progressively: no
  sitename: Casually Gaussian
  uselatex: yes
markup:
  goldmark:
    renderer:
      unsafe: yes
menu:
  primary:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: /about/
      weight: 2
#    - name: GitHub
#      url: https://github.com/nanxstats
#      weight: 3
#    - name: Twitter
#      url: https://twitter.com/nanxstats
#      weight: 4
#    - name: Subscribe
#      url: /index.xml
#      weight: 5
